# Generated by Django 5.2.15 on 2026-06-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceconfiguration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rawattendancelog',
            options={'ordering': ['-created_at']},
        ),
    ]
