# Generated by Django 5.2.15 on 2026-06-25 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_deviceconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfiguration',
            name='api_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
