# Generated by Django 5.2.15 on 2026-06-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employee_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
    ]
