# Generated by Django 5.2.15 on 2026-06-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_attendancerecord_anomaly_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='raw_logs',
        ),
    ]
