# Generated by Django 5.2.15 on 2026-06-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_company_remove_department_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Date of joining', null=True),
        ),
    ]
