# Generated by Django 5.2.15 on 2026-06-25 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_deviceconfiguration_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='api_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
